# Generated by Django 6.0.5 on 2026-05-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_quiz_score_quiz_user_alter_quiz_generated_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="attempted",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
