# Generated by Django 6.0.5 on 2026-05-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("docx", "DOCX"), ("txt", "TXT")],
                default="pdf",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
